# Generated by Django 5.2.7 on 2026-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_studentprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, default='School Fees', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, default='2025/2026', max_length=100),
        ),
    ]
